services:
  user-api-server:
    build: .
    image: user-api:v1
    container_name: user-api-server
    restart: always
    ports:
      - "8081:8081"
    networks:
      - miw

networks:
  miw:
    external: true


#> docker compose --build -d --no-recreate