services:
  user-api-server:
    build: .
    image: user-api:1.0.0
    container_name: user-api-server
    restart: always
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d